# Social Posting Agent Configuration
# API credentials and platform settings
# Last Updated: 2025-10-26

# ============================================
# TWITTER API CONFIGURATION
# ============================================
twitter:
  # All credentials loaded from .env file (project root)
  credentials_location: "{project-root}/.env"
  required_env_vars:
    - TWITTER_API_KEY
    - TWITTER_API_SECRET
    - TWITTER_ACCESS_TOKEN
    - TWITTER_ACCESS_TOKEN_SECRET

  # Rate limits (Twitter Free Tier)
  rate_limits:
    monthly_hard: 1500 # Hard API limit
    daily_recommended: 50 # Recommended to avoid flags
    hourly_recommended: 10 # Recommended pacing

  # Media specifications
  media:
    images:
      max_count: 4
      formats: [".jpg", ".jpeg", ".png", ".gif", ".webp"]
      max_size_mb: 5
      max_size_gif_mb: 15
    videos:
      max_count: 1 # Cannot mix with images
      formats: [".mp4", ".mov"]
      max_size_mb: 512
      encoding: "H.264"
      fps: "30-60"

  # Text specifications
  text:
    max_length_premium: 25000
    max_length_free: 280

  # Current account
  account_type: "premium" # Premium account features enabled
  status: "working" # Fully operational
  posts_made: 8 # Successful posts

# ============================================
# LINKEDIN API CONFIGURATION
# ============================================
linkedin:
  # Credentials in .env + token file
  credentials_location: "{project-root}/.env"
  token_file: "{project-root}/bmad/modules/linkedin-api-client/linkedin-token.json"
  required_env_vars:
    - LINKEDIN_CLIENT_ID
    - LINKEDIN_CLIENT_SECRET
    - LINKEDIN_REDIRECT_URI

  # OAuth status
  oauth:
    authenticated: true
    person_urn: "urn:li:person:H40RDQ7TNL"
    account_name: "Sid Dani"
    token_expires: "2025-12-25"
    account_type: "personal" # Posts to personal profile, not company page

  # Rate limits
  rate_limits:
    daily_hard: 150 # LinkedIn API limit
    hourly_recommended: 25 # Recommended pacing

  # Media specifications
  media:
    single_image:
      formats: [".jpg", ".jpeg", ".png", ".gif"]
      max_pixels: 36152320 # 36M pixels
    multi_image:
      min_count: 2
      max_count: 20
      display: "grid_carousel" # Grid on desktop, swipeable on mobile
    documents:
      formats: [".pdf", ".ppt", ".pptx", ".doc", ".docx"]
      max_size_mb: 100
      max_pages: 300
      display: "swipeable_carousel" # True carousel format
    videos:
      formats: [".mp4"]
      min_size_kb: 75
      max_size_mb: 500

  # Text specifications
  text:
    max_length: 3000
    optimal_length: "800-1600" # 150-300 words
    hook_length: 140 # Mobile truncation point
    best_practices: "First 140 chars = hook, use line breaks, 3-5 hashtags"

  # Current status
  status: "working" # Fully operational
  posts_made: 5 # Successful posts
  features:
    - "text_posts"
    - "single_image"
    - "multi_image_carousel" # 2-20 images
    - "pdf_carousel" # Presentations
    - "video_posts" # BONUS feature

# ============================================
# YOUTUBE API CONFIGURATION
# ============================================
youtube:
  # MCP server integration
  mcp_server: "youtube-uploader-mcp"
  oauth_file: "~/.config/youtube-uploader-mcp/client_secret_*.json"

  # Channel information
  channel:
    id: "UCeNChkI6YhgS4zFrjOICcLw"
    name: "Sid Dani"
    handle: "@siddani09"
    url: "https://www.youtube.com/@siddani09"

  # OAuth status
  oauth:
    authenticated: true
    tokens: "auto_managed" # MCP server handles refresh
    type: "desktop_app"

  # Quota & limits
  quotas:
    daily_units: 10000
    upload_cost: 1600 # units per upload
    max_uploads_per_day: 6 # ~10000/1600

  # Video specifications
  media:
    videos:
      max_size_gb: 256
      formats: "all_youtube_supported" # MP4, MOV, AVI, etc.
      processing: "automatic" # YouTube processes after upload
    shorts:
      aspect_ratio: "9:16 or 1:1"
      max_duration_sec: 180 # 3 minutes (updated Oct 2024)
      resolution: "1080x1920 recommended"
      auto_detection: true # No special params needed

  # Privacy restrictions
  privacy:
    default: "private" # Unverified app restriction
    manual_publish: true # Must change to Public in Studio
    note: "App verification needed for auto-public uploads (4-6 weeks)"

  # Current status
  status: "working" # Authenticated and functional
  videos_uploaded: 1 # Successful uploads
  features:
    - "regular_videos"
    - "youtube_shorts" # Auto-detected
    - "custom_metadata" # Title, description, tags, category

# ============================================
# MODULE PATHS
# ============================================
modules:
  twitter_client: "{project-root}/bmad/modules/twitter-api-client"
  linkedin_client: "{project-root}/bmad/modules/linkedin-api-client"

# ============================================
# OUTPUT SETTINGS
# ============================================
output:
  twitter_rate_state: "{project-root}/bmad/modules/twitter-api-client/.rate-limit-state.json"
  linkedin_rate_state: "{project-root}/bmad/modules/linkedin-api-client/.rate-limit-state.json"
  linkedin_token: "{project-root}/bmad/modules/linkedin-api-client/linkedin-token.json"
  log_posts: true
  log_location: "{agent-folder}/social-posting-agent-sidecar/post-history.json"

# ============================================
# AGENT BEHAVIOR
# ============================================
agent:
  default_warnings:
    rate_limit_warning_threshold: 0.9 # Warn at 90% of limit
    confirm_before_bulk_post: true # Ask before posting 5+ items
    validate_before_post: true # Always validate inputs
    show_preview: true # Show preview before posting

  error_handling:
    retry_on_network_error: true
    max_retries: 3
    retry_delay_seconds: 5
    graceful_degradation: true # Continue multi-post operations on single failure
    structured_responses: true # Always return {success, ...}

  user_experience:
    show_rate_limits: true # Display limits after posting
    show_post_urls: true # Display URLs of posted content
    show_character_count: true # Show character count
    show_upload_progress: true # Show progress for large uploads
    accessibility_prompts: true # Ask for alt text

  validation:
    check_file_exists: true
    check_file_size: true
    check_file_format: true
    check_text_length: true
    check_rate_limits: true

# ============================================
# PLATFORM STATUS SUMMARY
# ============================================
status:
  overall: "production_ready"
  platforms_working: 3
  platforms_planned: 2

  twitter:
    status: "working"
    implementation: "custom_module"
    tested: true
    posts_successful: 8

  linkedin:
    status: "working"
    implementation: "custom_module"
    tested: true
    posts_successful: 5

  youtube:
    status: "working"
    implementation: "mcp_server"
    tested: true
    uploads_successful: 1

  instagram:
    status: "planned"
    implementation: "tbd"

  tiktok:
    status: "planned"
    implementation: "tbd"

# ============================================
# WORKFLOWS
# ============================================
workflows:
  total: 10

  twitter: 4
  twitter_list:
    - post-text-tweet.yaml
    - post-tweet-with-image.yaml
    - post-tweet-with-video.yaml
    - create-thread.yaml

  linkedin: 4
  linkedin_list:
    - linkedin-post-text.yaml
    - linkedin-post-image.yaml
    - linkedin-post-multiimage.yaml
    - linkedin-post-pdf.yaml

  youtube: 2
  youtube_list:
    - youtube-upload-video.yaml
    - youtube-upload-short.yaml

# ============================================
# COMMANDS
# ============================================
commands:
  total: 12

  twitter_commands:
    - tweet # Text post
    - tweet-image # With images
    - tweet-video # With video
    - thread # Multi-tweet
    - check-limits # Rate limit stats
    - verify-credentials # Test connection

  linkedin_commands:
    - linkedin-text # Text post
    - linkedin-image # Single image
    - linkedin-carousel # 2-20 images
    - linkedin-pdf # PDF carousel

  youtube_commands:
    - youtube-video # Regular video
    - youtube-short # Shorts (auto-detect)
