name: competitive-analysis
description: "Multi-profile comparison with gap analysis and strategic recommendations"
author: "Jarvis"

# Variables
config_source: "{agent-folder}/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
installed_path: "{agent-folder}/workflows/competitive-analysis"
skills_folder: "{project-root}/.claude/skills/jarvis"

# MCP Tools
# Note: All scraping via Apify (broken MCPs removed: linkedin-mcp, youtube_mcp_server)
mcp_tools_required:
  - apify: [call-actor, get-actor-output] # For all platforms (Instagram, LinkedIn, TikTok, Twitter, YouTube)

# Custom Modules
custom_modules:
  - twitter_api_client: "For your Twitter profile"

# Inputs
inputs:
  - your_profiles: "Array of YOUR profile URLs (1-3)"
  - competitor_profiles: "Array of competitor URLs (max 5)"
  - comparison_metrics: "engagement|frequency|topics|formats|all (default: all)"
  - generate_action_plan: "boolean, create 7-day content plan (default: true)"

# Outputs
outputs:
  - comparison_matrix: "Side-by-side metrics table"
  - gap_analysis: "Topic, format, hook, timing gaps"
  - differentiation_strategy: "3 strategic recommendations"
  - seven_day_plan: "Specific content ideas mapped to gaps"
  - cost_summary: "Total API cost for all profile analyses"

# Action workflow
template: false
instructions: "{installed_path}/instructions.md"

# Output files
# Note: Actual output path created dynamically in Step 0 of instructions.md
# Pattern: outputs/projects/{YYYY-MM-DD}-competitive-analysis/01-research/competitive-analysis.md
default_output_file: "{project-root}/outputs/projects/{date}-competitive-analysis/01-research/competitive-analysis.md"
