# Edit Skill - Workflow Configuration
name: "edit-skill"
description: "Edit existing Claude Code skills while maintaining consistency across SKILL.md, supporting files, and all project manifests. Automatically discovers and updates all usage locations in workflows and agents."
author: "BMad Builder"

# Critical variables from config
config_source: "{project-root}/bmad/bmb/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Required data files - Manifests for loading and updating
agent_manifest: "{project-root}/bmad/_cfg/agent-manifest.csv"
workflow_manifest: "{project-root}/bmad/_cfg/workflow-manifest.csv"
skill_manifest: "{project-root}/bmad/_cfg/skill-manifest.csv"
files_manifest: "{project-root}/bmad/_cfg/files-manifest.csv"

# Reference materials
anthropic_best_practices: "{project-root}/bmad/bmb/workflows/create-skill/anthropic-best-practices.md"
research_context: "{project-root}/bmad/bmb/workflows/create-skill/research-context.md"

# Module path and component files
installed_path: "{project-root}/bmad/bmb/workflows/edit-skill"
template: false # Action workflow - edits existing files, no template
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Skill paths
skill_output_base: "{project-root}/.claude/skills"

# Search paths for finding skill usage
search_paths:
  - "{project-root}/bmad/*/agents/*.md"
  - "{project-root}/bmad/*/agents/*.yaml"
  - "{project-root}/bmad/*/workflows/*/instructions.md"
  - "{project-root}/bmad/*/README.md"
  - "{project-root}/.claude/commands/**/*.md"

# Tool Requirements
required_tools:
  - "Exa Search":
      description: "Neural search for finding updated methodologies (optional re-research)"
      link: "https://exa.ai"
  - "Firecrawl":
      description: "Web scraping for updated content (optional re-research)"
      link: "https://firecrawl.dev"
  - "Grep":
      description: "Required for finding skill usage across codebase"
      link: "built-in"

# Invocation control
standalone: true

# Web Bundle Configuration
web_bundle:
  name: 'edit-skill'
  description: 'Edit existing Claude Code skills while maintaining consistency across SKILL.md, supporting files, and all project manifests. Automatically discovers and updates all usage locations in workflows and agents.'
  author: 'BMad Builder'

  instructions: 'bmad/bmb/workflows/edit-skill/instructions.md'
  validation: 'bmad/bmb/workflows/edit-skill/checklist.md'
  template: false

  # Required data files
  skill_manifest: 'bmad/_cfg/skill-manifest.csv'
  agent_manifest: 'bmad/_cfg/agent-manifest.csv'
  anthropic_best_practices: 'bmad/bmb/workflows/create-skill/anthropic-best-practices.md'
  research_context: 'bmad/bmb/workflows/create-skill/research-context.md'

  web_bundle_files:
    - 'bmad/bmb/workflows/edit-skill/instructions.md'
    - 'bmad/bmb/workflows/edit-skill/checklist.md'
    - 'bmad/bmb/workflows/create-skill/anthropic-best-practices.md'
    - 'bmad/bmb/workflows/create-skill/research-context.md'
    - 'bmad/_cfg/skill-manifest.csv'
    - 'bmad/_cfg/agent-manifest.csv'
