# AI Image Generator Module Configuration
# BMAD v6 Standard Config Block
# Date: 2025-10-27

# Standard BMAD Configuration Values (REQUIRED)
user_name: sid
communication_language: english
document_output_language: english
output_folder: "{project-root}/docs/ai-image-generator"

# Module Metadata
module_name: ai-image-generator
module_type: agent
module_version: "1.0.0"

# Module-Specific Paths
sidecar_folder: "{project-root}/bmad/agents/ai-image-generator/ai-image-generator-sidecar"
sidecar_config: "{project-root}/bmad/agents/ai-image-generator/ai-image-generator-sidecar/config.yaml"
workflows_folder: "{project-root}/bmad/agents/ai-image-generator/workflows"
outputs_folder: "{project-root}/bmad/agents/ai-image-generator/ai-image-generator-sidecar/outputs"
templates_folder: "{project-root}/bmad/agents/ai-image-generator/ai-image-generator-sidecar/templates"

# Skills Configuration
skills_folder: "{project-root}/.claude/skills/ai-image-generator"
skills_enabled: true

# Knowledge Base References
capabilities_doc: "{project-root}/bmad/agents/ai-image-generator/ai-image-generator-sidecar/MCP_CAPABILITIES.md"
best_practices_doc: "{project-root}/bmad/agents/ai-image-generator/ai-image-generator-sidecar/best-practices-framework.md"
platform_specs_doc: "{project-root}/bmad/agents/ai-image-generator/ai-image-generator-sidecar/platform-specs.yaml"

# Default Settings (can be overridden by workflows)
default_provider: openai  # Options: openai, nanobanana
default_platform: instagram
default_quality: high
default_format: png

# MCP Tool Configuration
mcp_tools:
  gpt_image_1:
    enabled: true
    tool_name: "mcp__gpt-image-1__create_image"
  nanobanana:
    enabled: true
    tool_name: "mcp__nanobanana__generate_image"

# Note: API keys and advanced provider settings are stored in sidecar_config
# This separation keeps sensitive data isolated and module config clean
