name: analyze-profile
description: "Deep profile analysis on ANY platform with pattern extraction and evidence"
author: "Jarvis"

# Variables
config_source: "{agent-folder}/config.yaml"
output_folder: "{config_source}:output_folder"
sessions_folder: "{config_source}:sessions_folder"
date: system-generated
installed_path: "{agent-folder}/workflows/analyze-profile"

# MCP Tools
# Note: All scraping via Apify (Instagram, LinkedIn, TikTok, Twitter, YouTube)
# Note: linkedin-mcp and ig-mcp are broken - removed
mcp_tools_required:
  - apify: [search-actors, fetch-actor-details, call-actor, get-actor-output]
  - exa: [web_search] # For username verification

# Custom Modules
custom_modules:
  - twitter_api_client: "For analyzing YOUR Twitter account (free)"

# Inputs
inputs:
  - profile_url: "URL to analyze (required)"
  - platform: "auto-detect or specify: twitter|instagram|tiktok|linkedin|youtube"
  - window_days: "Analysis window in days (default: 90)"
  - analysis_depth: "quick|standard|deep (default: standard)"
  - extract_transcripts: "boolean, for YouTube only (default: true)"
  - is_your_profile: "boolean, use free APIs if true (default: false)"

# Outputs
outputs:
  - profile_summary: "Bio, metrics, posting cadence"
  - content_strategy: "Content mix, topics, hooks, timing"
  - top_performers: "Top 10 posts with engagement + URLs"
  - pattern_library: "Winning patterns across hooks, formats, topics"
  - recommendations: "5-7 actionable recommendations with evidence"
  - cost_log: "API usage and cost for this analysis"

# Action workflow
template: false
instructions: "{installed_path}/instructions.md"

# Output files
default_output_file: "{sessions_folder}/profile-analysis-{platform}-{handle}-{date}.md"
