name: analyze-profile
description: 'Deep profile analysis on ANY platform with pattern extraction and evidence'
author: 'Jarvis'

# Variables
config_source: '{agent-folder}/config.yaml'
output_folder: '{config_source}:output_folder'
sessions_folder: '{config_source}:sessions_folder'
date: system-generated
installed_path: '{agent-folder}/workflows/analyze-profile'

# MCP Tools (Multi-tier approach)
mcp_tools_required:
  # Tier 1: FREE
  - youtube_mcp_server: [get_channel_details, get_channel_videos, analyze_video_engagement]
  - youtube_transcript: [get_transcript]

  # Tier 2: Low-cost
  - linkedin_mcp: [fetch_and_save_linkedin_posts, get_top_posts, search_posts, get_posts_by_date]
  - exa_mcp: [linkedin_search]

  # Tier 3: Apify (pay-per-use)
  - apify_mcp: [search-actors, fetch-actor-details, call-actor, get-actor-output]

# Custom Modules
custom_modules:
  - twitter_api_client: 'For analyzing YOUR Twitter account (free)'

# Inputs
inputs:
  - profile_url: 'URL to analyze (required)'
  - platform: 'auto-detect or specify: twitter|instagram|tiktok|linkedin|youtube'
  - window_days: 'Analysis window in days (default: 90)'
  - analysis_depth: 'quick|standard|deep (default: standard)'
  - extract_transcripts: 'boolean, for YouTube only (default: true)'
  - is_your_profile: 'boolean, use free APIs if true (default: false)'

# Outputs
outputs:
  - profile_summary: 'Bio, metrics, posting cadence'
  - content_strategy: 'Content mix, topics, hooks, timing'
  - top_performers: 'Top 10 posts with engagement + URLs'
  - pattern_library: 'Winning patterns across hooks, formats, topics'
  - recommendations: '5-7 actionable recommendations with evidence'
  - cost_log: 'API usage and cost for this analysis'

# Action workflow
template: false
instructions: '{installed_path}/instructions.md'

# Output files
default_output_file: '{sessions_folder}/profile-analysis-{platform}-{handle}-{date}.md'
