name: generate-ideas
description: "Generate evidence-backed Idea Cards with hooks, outlines, and platform recommendations"
author: "Jarvis"

# Variables
config_source: "{agent-folder}/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
installed_path: "{agent-folder}/workflows/generate-ideas"
skills_folder: "{project-root}/.claude/skills/jarvis"

# MCP Tools
# Note: Research Skills handle note-taking and summarization automatically
mcp_tools_required:
  - social_media_mcp: [get_trending_topics, research_topic]
  - exa_mcp: [web_search_exa, deep_researcher_start, deep_researcher_check]

# Inputs
inputs:
  - seed_topic: "Main topic or theme (required)"
  - target_platforms: "Array: [twitter, instagram, tiktok, linkedin, youtube, reels] (default: all)"
  - competitor_urls: "Optional: Competitor profile URLs to analyze for gaps"
  - idea_count: "Number of ideas to generate (default: 10)"
  - style: "tutorial|opinion|story|teardown|announcement|mixed (default: mixed)"
  - use_trends: "boolean, incorporate trending topics (default: true)"
  - use_research_file: "Optional: Path to research-topic output to use as source"

# Outputs
outputs:
  - idea_cards: "Structured ideas with hooks, outlines, evidence"
  - hook_pack: "10+ hook variations for quick use"
  - content_calendar: "7-14 day posting schedule"
  - evidence_summary: "All sources cited"

# Action workflow
template: false
instructions: "{installed_path}/instructions.md"

# Output files
# Note: Actual output path created dynamically in Step 0 of instructions.md
# Pattern: outputs/projects/{YYYY-MM-DD}-{topic-slug}/02-ideas/idea-cards.md
default_output_file: "{project-root}/outputs/projects/{date}-{topic-slug}/02-ideas/idea-cards.md"
