name: research-topic
description: 'Deep topic research with multi-source intelligence aggregation'
author: 'Jarvis'

# Variables
config_source: '{agent-folder}/config.yaml'
output_folder: '{config_source}:output_folder'
sessions_folder: '{config_source}:sessions_folder'
knowledge_folder: '{config_source}:knowledge_folder'
user_name: '{config_source}:user_name'
date: system-generated

# Workflow location
installed_path: '{agent-folder}/workflows/research-topic'

# MCP Tools (Tier 1 & 2 only - all free or low-cost)
mcp_tools_required:
  - script_generation_mcp: [add_note, summarize_notes]
  - exa_mcp: [web_search_exa, deep_researcher_start, deep_researcher_check]
  - social_media_mcp: [get_trending_topics, research_topic]
  - youtube_transcript: [get_transcript]

# Inputs
inputs:
  - topic: 'Main research topic (required)'
  - depth: 'quick|standard|comprehensive (default: standard)'
  - focus_areas: 'Array: [trends, examples, data, quotes, competitors] (default: all)'
  - output_format: 'notes|report|idea-cards (default: report)'
  - max_youtube_videos: 'Max videos to analyze for examples (default: 5)'

# Outputs
outputs:
  - research_brief: 'Executive summary with key findings'
  - content_angles: '10+ ways to approach this topic'
  - research_notes: 'All gathered data organized by category'
  - quotes_library: 'Attributed quotes with sources'
  - data_points: 'Statistics and metrics'

# Action workflow (no template file)
template: false
instructions: '{installed_path}/instructions.md'

# Output files
default_output_file: '{sessions_folder}/research-{topic}-{date}.md'
notes_file: '{sessions_folder}/research-{topic}-notes-{date}.md'
