name: research-topic
description: "Deep topic research with multi-source intelligence aggregation"
author: "Jarvis"

# Variables
config_source: "{agent-folder}/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Workflow location
installed_path: "{agent-folder}/workflows/research-topic"

# MCP Tools (Tier 1 & 2 only - all free or low-cost)
# Note: Research is now handled by Claude Code Skills (autonomous invocation)
# Note: YouTube transcripts now use Apify (youtube-transcript MCP is broken)
mcp_tools_required:
  - exa_mcp: [web_search_exa, deep_researcher_start, deep_researcher_check]
  - social_media_mcp: [get_trending_topics, research_topic]
  - apify: [call-actor] # For YouTube transcripts via karamelo/youtube-transcripts

# Inputs
inputs:
  - topic: "Main research topic (required)"
  - depth: "quick|standard|comprehensive (default: standard)"
  - focus_areas: "Array: [trends, examples, data, quotes, competitors] (default: all)"
  - output_format: "notes|report|idea-cards (default: report)"
  - max_youtube_videos: "Max videos to analyze for examples (default: 5)"

# Outputs
outputs:
  - research_brief: "Executive summary with key findings"
  - content_angles: "10+ ways to approach this topic"
  - research_notes: "All gathered data organized by category"
  - quotes_library: "Attributed quotes with sources"
  - data_points: "Statistics and metrics"

# Action workflow (no template file)
template: false
instructions: "{installed_path}/instructions.md"

# Output files
# Note: Actual output path created dynamically in Step 0 of instructions.md
# Pattern: outputs/projects/{YYYY-MM-DD}-{topic-slug}/01-research/research-brief.md
default_output_file: "{project-root}/outputs/projects/{date}-{topic-slug}/01-research/research-brief.md"
