name: learn-voice-enhanced
description: "Deep rhetorical DNA analysis to build authentic voice profile with mode detection and argument architecture"
author: "Jarvis"
version: "2.0"
updated: "2025-10-28"

# Variables
config_source: "{agent-folder}/config.yaml"
output_folder: "{config_source}:output_folder"
date: system-generated
installed_path: "{agent-folder}/workflows/learn-voice"

# MCP Tools
# Note: All scraping via Apify (broken MCPs removed: linkedin-mcp, youtube_mcp_server, youtube_transcript)
# Note: mcp_twitter used as primary for Twitter (free), Apify as fallback
mcp_tools_required:
  - mcp_twitter: [get_last_tweet_from_user] # Primary for Twitter (free)
  - apify: [call-actor, get-actor-output] # For LinkedIn, YouTube, and Twitter fallback
  - apify_actors:
      twitter: "scraper_one/x-profile-posts-scraper" # Reliable, returns 50-100 posts
      linkedin: "apimaestro/linkedin-profile-posts" # NO COOKIES, reliable
      youtube: "starvibe/youtube-video-transcript" # Transcript extraction

# Custom Modules (FREE for user's own account)
custom_modules:
  - twitter_api_client: "Fetch YOUR tweets (preferred - free)"

# Inputs
inputs:
  - user_twitter_handle: "Your Twitter @handle (optional)"
  - user_linkedin_url: "Your LinkedIn profile URL (optional)"
  - user_youtube_channel: "Your YouTube channel URL (optional)"
  - min_posts_required: "Minimum posts for accurate profile (default: 30, recommended: 50+)"
  - include_video_voice: "boolean, analyze spoken voice from videos (default: true if YouTube provided)"
  - reference_voice_url: "Optional: URL to reference writer's style to blend (e.g., debarghyadas.com)"

# Outputs
outputs:
  - voice_profile_enhanced: "Comprehensive rhetorical DNA profile with voice modes"
  - argument_architecture: "How user builds and structures arguments"
  - voice_modes: "Detected writing modes with switching rules"
  - signature_elements: "Commonly used phrases and rhetorical devices"
  - platform_variations: "How voice changes per platform"
  - confidence_score: "Profile accuracy rating (based on sample size and depth)"

# Enhanced Analysis Dimensions (v2.0)
analysis_dimensions:
  # LEGACY (Surface Patterns - Keep)
  - vocabulary_analysis: "Technical term frequency, complexity level"
  - sentence_structure: "Length distribution, rhythm patterns"
  - tone_markers: "Formality, humor, enthusiasm indicators"
  - signature_phrases: "Repeated expressions, transitions"
  - emoji_usage: "Frequency, placement, types"
  - hook_preferences: "Opening strategies distribution"

  # NEW (Rhetorical DNA - Added v2.0)
  - argument_architecture: "Multi-act structure, thesis → qualification → proof → close"
  - voice_mode_detection: "Content-based mode switching (Analyst/Casual/Protector/Satirist/Enthusiast)"
  - structural_frameworks: "Eras, numbered lists, comparative structures"
  - proof_style: "Specificity ratio, named entities, personal experience, enumeration"
  - humor_mechanics: "Satire detection, hyperbole patterns, deadpan vs explicit"
  - emotional_range: "Enthusiasm, frustration, qualification, protective language"
  - closing_patterns: "CTAs, energy markers, forward-looking statements"
  - parenthetical_analysis: "Frequency, content type, depth-adding function"
  - cultural_voice: "Community language, bilingual elements, insider framing"
  - comparative_lens: "X vs Y frequency, competitive framing, differentiation"

# Action workflow
template: false
instructions: "{installed_path}/instructions.md"

# Voice profile saves to memories.md (not separate file)
voice_profile_location: "{agent-folder}/memories.md"

# Enhanced profile includes mode-specific templates
include_mode_templates: true

# Quality thresholds
quality_requirements:
  min_posts_for_mode_detection: 20 # Need 20+ to detect voice modes
  min_posts_for_rhetoric_analysis: 30 # Need 30+ for argument architecture
  min_posts_for_high_confidence: 50 # 50+ posts = 8/10 confidence
  min_long_form_posts: 5 # Need 5+ posts > 500 chars for deep analysis
