name: write-posts
description: 'Write platform-specific social media posts in user authentic voice'
author: 'Jarvis'

# Variables
config_source: '{agent-folder}/config.yaml'
output_folder: '{config_source}:output_folder'
platform_specs: '{config_source}:platforms'
voice_profile_location: '{agent-folder}/memories.md'
date: system-generated
installed_path: '{agent-folder}/workflows/write-posts'

# MCP Tools
mcp_tools_required:
  - script_generation_mcp: [script_generate, add_note]

# Custom Modules
custom_modules:
  - twitter_api_client: 'Validation (char limits, format)'
  - linkedin_api_client: 'Text formatting and escaping'

# Inputs
inputs:
  - idea_card_id: 'Reference to Idea Card OR idea_card_file path (required)'
  - target_platform: 'linkedin|twitter|instagram (required)'
  - tone_override: 'direct|playful|formal|casual (default: use voice profile)'
  - format_preference: 'For Twitter: long-form|thread|auto (default: auto)'
  - inject_evidence: 'boolean, include research quotes (default: true)'
  - generate_hook_variants: 'boolean, create 3 alternatives (default: true)'

# Outputs
outputs:
  - formatted_post: 'Platform-ready post text'
  - hook_variants: '3 alternative hook options'
  - metadata: 'Hashtags, length, posting tips'
  - handoff_package: 'JSON for Social Posting Agent'

# Action workflow
template: false
instructions: '{installed_path}/instructions.md'

# Output files
default_output_file: '{output_folder}/{platform}-post-{date}.md'
handoff_file: '{output_folder}/{platform}-post-handoff-{date}.json'
